package extractors

import (
	"strings"
	"testing"
)

func TestRTFExtractorSimpleDocument(t *testing.T) {
	t.Parallel()
	// Minimal RTF generated by LibreOffice-style output.
	rtf := `{\rtf1\ansi\ansicpg1252\deff0{\fonttbl{\f0\fnil Times;}}
\pard\f0 Hello world.\par
This is a test.\par
}`
	e := NewRTFExtractor()
	chunks, err := e.Extract(strings.NewReader(rtf), 0)
	if err != nil {
		t.Fatalf("Extract: %v", err)
	}
	if len(chunks) == 0 {
		t.Fatal("expected non-empty chunks")
	}
	combined := strings.Join(chunkTexts(chunks), "\n")
	if !strings.Contains(combined, "Hello world") {
		t.Errorf("missing 'Hello world' in %q", combined)
	}
	if !strings.Contains(combined, "This is a test") {
		t.Errorf("missing 'This is a test' in %q", combined)
	}
}

func TestRTFExtractorSkipsFontTable(t *testing.T) {
	t.Parallel()
	// The \fonttbl group should be skipped entirely; its contents
	// ("NotInOutput") must not leak into the extracted text.
	rtf := `{\rtf1\ansi{\fonttbl{\f0\fnil NotInOutput;}{\f1\fnil AlsoNotInOutput;}}
Text after the font table.\par}`
	e := NewRTFExtractor()
	chunks, err := e.Extract(strings.NewReader(rtf), 0)
	if err != nil {
		t.Fatalf("Extract: %v", err)
	}
	combined := strings.Join(chunkTexts(chunks), "\n")
	if strings.Contains(combined, "NotInOutput") {
		t.Errorf("fonttbl leaked into output: %q", combined)
	}
	if !strings.Contains(combined, "Text after the font table") {
		t.Errorf("body text missing: %q", combined)
	}
}

func TestRTFExtractorUnicodeEscape(t *testing.T) {
	t.Parallel()
	// \u233? should decode to é (codepoint 233). The trailing '?'
	// is the ASCII fallback character which we skip.
	rtf := `{\rtf1\ansi Caf\u233? con leche.\par}`
	e := NewRTFExtractor()
	chunks, err := e.Extract(strings.NewReader(rtf), 0)
	if err != nil {
		t.Fatalf("Extract: %v", err)
	}
	combined := strings.Join(chunkTexts(chunks), "\n")
	if !strings.Contains(combined, "Café") {
		t.Errorf("expected 'Café' in output, got %q", combined)
	}
}

func TestRTFExtractorRejectsNonRTF(t *testing.T) {
	t.Parallel()
	e := NewRTFExtractor()
	_, err := e.Extract(strings.NewReader("this is just plain text"), 0)
	if err == nil {
		t.Error("expected error for non-RTF input")
	}
}

func chunkTexts(cs []Chunk) []string {
	out := make([]string, len(cs))
	for i, c := range cs {
		out[i] = c.Text
	}
	return out
}
