package reputation

import (
	"bytes"
	"encoding/hex"
	"math"
	"testing"
)

// goldenVectorHex is the frozen 48-byte on-disk encoding of a
// NewBloomFilter(16, 0.01) (m=154, k=7, bitsLen=3) after adding the
// three canonical infohashes below, in order. It was regenerated by
// running the legacy bloom.go directly. A byte for byte match here
// proves this rebuild stays compatible with existing
// known-good.bloom files.
const goldenVectorHex = "53424c4d010007009a000000000000000300000000000000280004000010020113800000004889200800000000000000"

// goldenVectorItems are the three 20-byte infohashes added, in order.
func goldenVectorItems() [][]byte {
	ih1 := bytes.Repeat([]byte{0x00}, 20)
	ih2 := bytes.Repeat([]byte{0x01}, 20)
	ih3 := make([]byte, 20)
	for i := range ih3 {
		ih3[i] = byte(i) // 0x00 .. 0x13
	}
	return [][]byte{ih1, ih2, ih3}
}

// TestBloomGoldenVector pins the frozen FNV-64a v1 format end to
// end: sizing, per-word bitset contents, population count, the
// item estimate, and the exact serialized bytes.
func TestBloomGoldenVector(t *testing.T) {
	t.Parallel()
	bf := NewBloomFilter(16, 0.01)

	if bf.m != 154 || bf.k != 7 {
		t.Fatalf("sizing = m%d k%d, want m154 k7", bf.m, bf.k)
	}
	if len(bf.bits) != 3 {
		t.Fatalf("bitsLen = %d, want 3", len(bf.bits))
	}

	for _, ih := range goldenVectorItems() {
		bf.Add(ih)
	}

	wantBits := [3]uint64{0x0102100000040028, 0x2089480000008013, 0x0000000000000008}
	for i, w := range wantBits {
		if bf.bits[i] != w {
			t.Errorf("bits[%d] = %#016x, want %#016x", i, bf.bits[i], w)
		}
	}

	if pop := bf.PopulationCount(); pop != 17 {
		t.Errorf("PopulationCount = %d, want 17", pop)
	}
	if est := bf.EstimatedItems(); math.Abs(est-2.5734) > 1e-3 {
		t.Errorf("EstimatedItems = %.4f, want ~2.5734", est)
	}

	// Every added item must still test positive.
	for i, ih := range goldenVectorItems() {
		if !bf.Test(ih) {
			t.Errorf("item %d not present after Add", i)
		}
	}

	// Exact serialized bytes.
	var buf bytes.Buffer
	if err := writeBloom(&buf, bf); err != nil {
		t.Fatalf("writeBloom: %v", err)
	}
	if got := hex.EncodeToString(buf.Bytes()); got != goldenVectorHex {
		t.Errorf("serialized bytes mismatch:\n got  %s\n want %s", got, goldenVectorHex)
	}
	if buf.Len() != 48 {
		t.Errorf("file length = %d, want 48", buf.Len())
	}
}
